# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - name: "Hello World"
        run: echo "Hola Mundoo"
      - name: Dime la hora
        run: echo "La hora es $(date)"
      - name: Contenido del directorio
        run: ls -la
